time="2022-04-21T11:38:27Z" level=info msg="Configuration loaded from file: /etc/traefik/traefik.yml"
time="2022-04-21T11:38:27Z" level=info msg="Traefik version 2.3.7 built on 2021-01-11T18:03:02Z"
time="2022-04-21T11:38:27Z" level=debug msg="Static configuration loaded {\"global\":{\"checkNewVersion\":true},\"serversTransport\":{\"maxIdleConnsPerHost\":200},\"entryPoints\":{\"traefik\":{\"address\":\":8080\",\"transport\":{\"lifeCycle\":{\"graceTimeOut\":10000000000},\"respondingTimeouts\":{\"idleTimeout\":180000000000}},\"forwardedHeaders\":{},\"http\":{}},\"web\":{\"address\":\":80\",\"transport\":{\"lifeCycle\":{\"graceTimeOut\":10000000000},\"respondingTimeouts\":{\"idleTimeout\":180000000000}},\"forwardedHeaders\":{},\"http\":{}},\"websecure\":{\"address\":\":443\",\"transport\":{\"lifeCycle\":{\"graceTimeOut\":10000000000},\"respondingTimeouts\":{\"idleTimeout\":180000000000}},\"forwardedHeaders\":{},\"http\":{}}},\"providers\":{\"providersThrottleDuration\":2000000000,\"docker\":{\"watch\":true,\"endpoint\":\"unix:///var/run/docker.sock\",\"defaultRule\":\"Host(`{{ normalize .Name }}`)\",\"swarmModeRefreshSeconds\":15000000000}},\"api\":{\"insecure\":true,\"dashboard\":true},\"log\":{\"level\":\"DEBUG\",\"format\":\"common\"}}"
time="2022-04-21T11:38:27Z" level=info msg="\nStats collection is disabled.\nHelp us improve Traefik by turning this feature on :)\nMore details on: https://doc.traefik.io/traefik/contributing/data-collection/\n"
time="2022-04-21T11:38:27Z" level=info msg="Starting provider aggregator.ProviderAggregator {}"
time="2022-04-21T11:38:27Z" level=debug msg="Start TCP Server" entryPointName=web
time="2022-04-21T11:38:27Z" level=debug msg="Start TCP Server" entryPointName=traefik
time="2022-04-21T11:38:27Z" level=debug msg="Start TCP Server" entryPointName=websecure
time="2022-04-21T11:38:27Z" level=info msg="Starting provider *traefik.Provider {}"
time="2022-04-21T11:38:27Z" level=info msg="Starting provider *docker.Provider {\"watch\":true,\"endpoint\":\"unix:///var/run/docker.sock\",\"defaultRule\":\"Host(`{{ normalize .Name }}`)\",\"swarmModeRefreshSeconds\":15000000000}"
time="2022-04-21T11:38:27Z" level=debug msg="Configuration received from provider internal: {\"http\":{\"routers\":{\"api\":{\"entryPoints\":[\"traefik\"],\"service\":\"api@internal\",\"rule\":\"PathPrefix(`/api`)\",\"priority\":2147483646},\"dashboard\":{\"entryPoints\":[\"traefik\"],\"middlewares\":[\"dashboard_redirect@internal\",\"dashboard_stripprefix@internal\"],\"service\":\"dashboard@internal\",\"rule\":\"PathPrefix(`/`)\",\"priority\":2147483645}},\"services\":{\"api\":{},\"dashboard\":{},\"noop\":{}},\"middlewares\":{\"dashboard_redirect\":{\"redirectRegex\":{\"regex\":\"^(http:\\\\/\\\\/(\\\\[[\\\\w:.]+\\\\]|[\\\\w\\\\._-]+)(:\\\\d+)?)\\\\/$\",\"replacement\":\"${1}/dashboard/\",\"permanent\":true}},\"dashboard_stripprefix\":{\"stripPrefix\":{\"prefixes\":[\"/dashboard/\",\"/dashboard\"]}}}},\"tcp\":{},\"tls\":{}}" providerName=internal
time="2022-04-21T11:38:27Z" level=debug msg="Added outgoing tracing middleware api@internal" middlewareType=TracingForwarder entryPointName=traefik routerName=api@internal middlewareName=tracing
time="2022-04-21T11:38:27Z" level=debug msg="Added outgoing tracing middleware dashboard@internal" entryPointName=traefik routerName=dashboard@internal middlewareName=tracing middlewareType=TracingForwarder
time="2022-04-21T11:38:27Z" level=debug msg="Creating middleware" routerName=dashboard@internal middlewareType=StripPrefix middlewareName=dashboard_stripprefix@internal entryPointName=traefik
time="2022-04-21T11:38:27Z" level=debug msg="Adding tracing to middleware" entryPointName=traefik routerName=dashboard@internal middlewareName=dashboard_stripprefix@internal
time="2022-04-21T11:38:27Z" level=debug msg="Creating middleware" middlewareName=dashboard_redirect@internal middlewareType=RedirectRegex routerName=dashboard@internal entryPointName=traefik
time="2022-04-21T11:38:27Z" level=debug msg="Setting up redirection from ^(http:\\/\\/(\\[[\\w:.]+\\]|[\\w\\._-]+)(:\\d+)?)\\/$ to ${1}/dashboard/" middlewareType=RedirectRegex routerName=dashboard@internal entryPointName=traefik middlewareName=dashboard_redirect@internal
time="2022-04-21T11:38:27Z" level=debug msg="Adding tracing to middleware" entryPointName=traefik routerName=dashboard@internal middlewareName=dashboard_redirect@internal
time="2022-04-21T11:38:27Z" level=debug msg="Creating middleware" entryPointName=traefik middlewareName=traefik-internal-recovery middlewareType=Recovery
time="2022-04-21T11:38:27Z" level=debug msg="No default certificate, generating one"
time="2022-04-21T11:38:27Z" level=debug msg="Provider connection established with docker 20.10.14 (API 1.41)" providerName=docker
time="2022-04-21T11:38:27Z" level=debug msg="Filtering disabled container" providerName=docker container=traefik-spike-demo-23b16926c3269dae56a35da6cbf28ff2b4ec58976a8f88f94377c6febc251449
time="2022-04-21T11:38:27Z" level=debug msg="Configuration received from provider docker: {\"http\":{\"routers\":{\"addedkey\":{\"entryPoints\":[\"web\"],\"middlewares\":[\"testHeader\"],\"service\":\"addedkey-spike-demo\",\"rule\":\"Host(`demo.localhost`) \\u0026\\u0026 Path(`/withkey`)\"},\"keyfromchain\":{\"entryPoints\":[\"web\"],\"middlewares\":[\"secured\"],\"service\":\"keyfromchain-spike-demo\",\"rule\":\"Host(`demo.localhost`) \\u0026\\u0026 Host(`demo.localhost.incorrect`) \\u0026\\u0026 Path(`/fromchain`)\"},\"keyfromchain2\":{\"entryPoints\":[\"web\"],\"middlewares\":[\"securedv2\"],\"service\":\"keyfromchain2-spike-demo\",\"rule\":\"Host(`demo.localhost`) \\u0026\\u0026 Host(`demo.localhost.correct`) \\u0026\\u0026 Path(`/fromchain`)\"},\"keyfromrequest\":{\"entryPoints\":[\"web\"],\"middlewares\":[\"tstAuth\"],\"service\":\"keyfromrequest-spike-demo\",\"rule\":\"Host(`demo.localhost`) \\u0026\\u0026 Path(`/direct`)\"},\"missingkey\":{\"entryPoints\":[\"web\"],\"service\":\"missingkey-spike-demo\",\"rule\":\"Host(`demonokeyprovided.localhost`) \\u0026\\u0026 Path(`/withkey`)\"},\"noapikey\":{\"entryPoints\":[\"web\"],\"service\":\"noapikey-spike-demo\",\"rule\":\"Host(`demo.localhost`) \\u0026\\u0026 Path(`/nokey`)\"}},\"services\":{\"addedkey-spike-demo\":{\"loadBalancer\":{\"servers\":[{\"url\":\"http://172.29.0.6:2222\"}],\"passHostHeader\":true}},\"keyfromchain-spike-demo\":{\"loadBalancer\":{\"servers\":[{\"url\":\"http://172.29.0.7:3333\"}],\"passHostHeader\":true}},\"keyfromchain2-spike-demo\":{\"loadBalancer\":{\"servers\":[{\"url\":\"http://172.29.0.3:3333\"}],\"passHostHeader\":true}},\"keyfromrequest-spike-demo\":{\"loadBalancer\":{\"servers\":[{\"url\":\"http://172.29.0.8:3333\"}],\"passHostHeader\":true}},\"missingkey-spike-demo\":{\"loadBalancer\":{\"servers\":[{\"url\":\"http://172.29.0.2:2222\"}],\"passHostHeader\":true}},\"noapikey-spike-demo\":{\"loadBalancer\":{\"servers\":[{\"url\":\"http://172.29.0.4:2222\"}],\"passHostHeader\":true}}},\"middlewares\":{\"correctHeader\":{\"headers\":{\"customRequestHeaders\":{\"x-api-key\":\"correctApiKey\"}}},\"secured\":{\"chain\":{\"middlewares\":[\"testHeader\",\"tstAuth\"]}},\"securedv2\":{\"chain\":{\"middlewares\":[\"correctHeader\",\"tstAuth\"]}},\"testHeader\":{\"headers\":{\"customRequestHeaders\":{\"x-api-key\":\"testapikey\"}}},\"tstAuth\":{\"forwardAuth\":{\"address\":\"https://mock-auth-traefik.herokuapp.com/auth\"}}}},\"tcp\":{},\"udp\":{}}" providerName=docker
time="2022-04-21T11:38:27Z" level=debug msg="Creating middleware" serviceName=keyfromrequest-spike-demo entryPointName=web routerName=keyfromrequest@docker middlewareName=pipelining middlewareType=Pipelining
time="2022-04-21T11:38:27Z" level=debug msg="Creating load-balancer" entryPointName=web routerName=keyfromrequest@docker serviceName=keyfromrequest-spike-demo
time="2022-04-21T11:38:27Z" level=debug msg="Creating server 0 http://172.29.0.8:3333" entryPointName=web routerName=keyfromrequest@docker serviceName=keyfromrequest-spike-demo serverName=0
time="2022-04-21T11:38:27Z" level=debug msg="Added outgoing tracing middleware keyfromrequest-spike-demo" entryPointName=web routerName=keyfromrequest@docker middlewareName=tracing middlewareType=TracingForwarder
time="2022-04-21T11:38:27Z" level=debug msg="Creating middleware" routerName=keyfromrequest@docker entryPointName=web middlewareName=tstAuth@docker middlewareType=ForwardedAuthType
time="2022-04-21T11:38:27Z" level=debug msg="Adding tracing to middleware" routerName=keyfromrequest@docker middlewareName=tstAuth@docker entryPointName=web
time="2022-04-21T11:38:27Z" level=debug msg="Creating middleware" serviceName=missingkey-spike-demo middlewareName=pipelining middlewareType=Pipelining entryPointName=web routerName=missingkey@docker
time="2022-04-21T11:38:27Z" level=debug msg="Creating load-balancer" entryPointName=web routerName=missingkey@docker serviceName=missingkey-spike-demo
time="2022-04-21T11:38:27Z" level=debug msg="Creating server 0 http://172.29.0.2:2222" entryPointName=web routerName=missingkey@docker serviceName=missingkey-spike-demo serverName=0
time="2022-04-21T11:38:27Z" level=debug msg="Added outgoing tracing middleware missingkey-spike-demo" middlewareType=TracingForwarder middlewareName=tracing entryPointName=web routerName=missingkey@docker
time="2022-04-21T11:38:27Z" level=debug msg="Creating middleware" entryPointName=web routerName=noapikey@docker middlewareName=pipelining middlewareType=Pipelining serviceName=noapikey-spike-demo
time="2022-04-21T11:38:27Z" level=debug msg="Creating load-balancer" routerName=noapikey@docker serviceName=noapikey-spike-demo entryPointName=web
time="2022-04-21T11:38:27Z" level=debug msg="Creating server 0 http://172.29.0.4:2222" entryPointName=web routerName=noapikey@docker serviceName=noapikey-spike-demo serverName=0
time="2022-04-21T11:38:27Z" level=debug msg="Added outgoing tracing middleware noapikey-spike-demo" middlewareName=tracing middlewareType=TracingForwarder entryPointName=web routerName=noapikey@docker
time="2022-04-21T11:38:27Z" level=debug msg="Creating middleware" middlewareName=pipelining middlewareType=Pipelining routerName=addedkey@docker entryPointName=web serviceName=addedkey-spike-demo
time="2022-04-21T11:38:27Z" level=debug msg="Creating load-balancer" routerName=addedkey@docker entryPointName=web serviceName=addedkey-spike-demo
time="2022-04-21T11:38:27Z" level=debug msg="Creating server 0 http://172.29.0.6:2222" entryPointName=web serverName=0 serviceName=addedkey-spike-demo routerName=addedkey@docker
time="2022-04-21T11:38:27Z" level=debug msg="Added outgoing tracing middleware addedkey-spike-demo" routerName=addedkey@docker middlewareName=tracing middlewareType=TracingForwarder entryPointName=web
time="2022-04-21T11:38:27Z" level=debug msg="Creating middleware" entryPointName=web routerName=addedkey@docker middlewareName=testHeader@docker middlewareType=Headers
time="2022-04-21T11:38:27Z" level=debug msg="Setting up customHeaders/Cors from {map[x-api-key:testapikey] map[] false [] []  [] [] 0 false [] [] false false  map[] false 0 false false false false  false false      false}" entryPointName=web routerName=addedkey@docker middlewareName=testHeader@docker middlewareType=Headers
time="2022-04-21T11:38:27Z" level=debug msg="Adding tracing to middleware" entryPointName=web routerName=addedkey@docker middlewareName=testHeader@docker
time="2022-04-21T11:38:27Z" level=debug msg="Creating middleware" entryPointName=web routerName=keyfromchain@docker serviceName=keyfromchain-spike-demo middlewareName=pipelining middlewareType=Pipelining
time="2022-04-21T11:38:27Z" level=debug msg="Creating load-balancer" routerName=keyfromchain@docker serviceName=keyfromchain-spike-demo entryPointName=web
time="2022-04-21T11:38:27Z" level=debug msg="Creating server 0 http://172.29.0.7:3333" entryPointName=web routerName=keyfromchain@docker serviceName=keyfromchain-spike-demo serverName=0
time="2022-04-21T11:38:27Z" level=debug msg="Added outgoing tracing middleware keyfromchain-spike-demo" routerName=keyfromchain@docker entryPointName=web middlewareName=tracing middlewareType=TracingForwarder
time="2022-04-21T11:38:27Z" level=debug msg="Creating middleware" entryPointName=web routerName=keyfromchain@docker middlewareType=Chain middlewareName=secured@docker
time="2022-04-21T11:38:27Z" level=debug msg="Creating middleware" middlewareName=tstAuth@docker middlewareType=ForwardedAuthType entryPointName=web routerName=keyfromchain@docker
time="2022-04-21T11:38:27Z" level=debug msg="Adding tracing to middleware" entryPointName=web routerName=keyfromchain@docker middlewareName=tstAuth@docker
time="2022-04-21T11:38:27Z" level=debug msg="Creating middleware" entryPointName=web middlewareName=testHeader@docker middlewareType=Headers routerName=keyfromchain@docker
time="2022-04-21T11:38:27Z" level=debug msg="Setting up customHeaders/Cors from {map[x-api-key:testapikey] map[] false [] []  [] [] 0 false [] [] false false  map[] false 0 false false false false  false false      false}" entryPointName=web middlewareName=testHeader@docker middlewareType=Headers routerName=keyfromchain@docker
time="2022-04-21T11:38:27Z" level=debug msg="Adding tracing to middleware" entryPointName=web routerName=keyfromchain@docker middlewareName=testHeader@docker
time="2022-04-21T11:38:27Z" level=debug msg="Creating middleware" entryPointName=web routerName=keyfromchain2@docker serviceName=keyfromchain2-spike-demo middlewareName=pipelining middlewareType=Pipelining
time="2022-04-21T11:38:27Z" level=debug msg="Creating load-balancer" entryPointName=web routerName=keyfromchain2@docker serviceName=keyfromchain2-spike-demo
time="2022-04-21T11:38:27Z" level=debug msg="Creating server 0 http://172.29.0.3:3333" serviceName=keyfromchain2-spike-demo entryPointName=web serverName=0 routerName=keyfromchain2@docker
time="2022-04-21T11:38:27Z" level=debug msg="Added outgoing tracing middleware keyfromchain2-spike-demo" middlewareType=TracingForwarder entryPointName=web routerName=keyfromchain2@docker middlewareName=tracing
time="2022-04-21T11:38:27Z" level=debug msg="Creating middleware" entryPointName=web routerName=keyfromchain2@docker middlewareName=securedv2@docker middlewareType=Chain
time="2022-04-21T11:38:27Z" level=debug msg="Creating middleware" routerName=keyfromchain2@docker middlewareType=ForwardedAuthType middlewareName=tstAuth@docker entryPointName=web
time="2022-04-21T11:38:27Z" level=debug msg="Adding tracing to middleware" middlewareName=tstAuth@docker routerName=keyfromchain2@docker entryPointName=web
time="2022-04-21T11:38:27Z" level=debug msg="Creating middleware" routerName=keyfromchain2@docker entryPointName=web middlewareName=correctHeader@docker middlewareType=Headers
time="2022-04-21T11:38:27Z" level=debug msg="Setting up customHeaders/Cors from {map[x-api-key:correctApiKey] map[] false [] []  [] [] 0 false [] [] false false  map[] false 0 false false false false  false false      false}" middlewareName=correctHeader@docker middlewareType=Headers routerName=keyfromchain2@docker entryPointName=web
time="2022-04-21T11:38:27Z" level=debug msg="Adding tracing to middleware" middlewareName=correctHeader@docker entryPointName=web routerName=keyfromchain2@docker
time="2022-04-21T11:38:27Z" level=debug msg="Creating middleware" entryPointName=web middlewareType=Recovery middlewareName=traefik-internal-recovery
time="2022-04-21T11:38:27Z" level=debug msg="Added outgoing tracing middleware api@internal" entryPointName=traefik routerName=api@internal middlewareName=tracing middlewareType=TracingForwarder
time="2022-04-21T11:38:27Z" level=debug msg="Added outgoing tracing middleware dashboard@internal" entryPointName=traefik routerName=dashboard@internal middlewareName=tracing middlewareType=TracingForwarder
time="2022-04-21T11:38:27Z" level=debug msg="Creating middleware" middlewareName=dashboard_stripprefix@internal middlewareType=StripPrefix entryPointName=traefik routerName=dashboard@internal
time="2022-04-21T11:38:27Z" level=debug msg="Adding tracing to middleware" middlewareName=dashboard_stripprefix@internal entryPointName=traefik routerName=dashboard@internal
time="2022-04-21T11:38:27Z" level=debug msg="Creating middleware" entryPointName=traefik routerName=dashboard@internal middlewareName=dashboard_redirect@internal middlewareType=RedirectRegex
time="2022-04-21T11:38:27Z" level=debug msg="Setting up redirection from ^(http:\\/\\/(\\[[\\w:.]+\\]|[\\w\\._-]+)(:\\d+)?)\\/$ to ${1}/dashboard/" entryPointName=traefik routerName=dashboard@internal middlewareName=dashboard_redirect@internal middlewareType=RedirectRegex
time="2022-04-21T11:38:27Z" level=debug msg="Adding tracing to middleware" entryPointName=traefik routerName=dashboard@internal middlewareName=dashboard_redirect@internal
time="2022-04-21T11:38:27Z" level=debug msg="Creating middleware" middlewareType=Recovery entryPointName=traefik middlewareName=traefik-internal-recovery
time="2022-04-21T11:38:27Z" level=debug msg="No default certificate, generating one"